---

- name: Elastic APT Key
  apt_key:
    state=present
    url="{{packetbeat_apt_key}}"

- name : PacketBeat APT Repository
  apt_repository:
    state=present
    repo="deb {{packetbeat_apt_repository}} stable main"
    update_cache=yes
  when: packetbeat_use_apt_repo

- name: Install PacketBeat (Debian)
  apt:
    state="{{ (packetbeat_upgrade) | ternary('latest', 'present') }}"
    name="{{item}}"
  with_items: "{{ packetbeat_packages }}"
  notify: packetbeat restart
  when: packetbeat_use_apt_repo

- name: Download PacketBeat .deb
  get_url:
    url: "{{ packetbeat_deb_baseurl }}/{{ item }}-{{ packetbeat_version }}-amd64.deb"
    dest: "/var/cache/apt/archives/{{ item }}-{{ packetbeat_version }}-amd64.deb"
  with_items: "{{ packetbeat_packages }}"
  when: not packetbeat_use_apt_repo

- name: Install PacketBeat .deb
  apt:
    deb: "/var/cache/apt/archives/{{ item }}-{{ packetbeat_version }}-amd64.deb"
    state: present
  with_items: "{{ packetbeat_packages }}"
  notify: packetbeat restart
  when: not packetbeat_use_apt_repo

# vi:ts=2:sw=2:et:ft=yaml
