---

- name: packetbeat | Create Solaris log directory and parents
  file:
    path: "{{ packetbeat_log_path }}"
    owner: "{{ packetbeat_user }}"
    group: "{{ packetbeat_group }}"
    state: directory
    recurse: yes
    mode: 0775

- name: packetbeat | Download Packetbeat agent package
  get_url:
    url: "{{ packetbeat_solaris_url }}"
    dest: "/tmp/packetbeat-{{ packetbeat_version }}.pkg"
    mode: 0550

- name:  packetbeat | Install Packetbeat agent for Solaris
  svr4pkg:
    name: packetbeat
    src: "/tmp/packetbeat-{{ packetbeat_version }}.pkg"
    state: present

- name: packetbeat | Install Packetbeat service
  shell: (svccfg import /opt/packetbeat/etc/packetbeat.xml) && (svcs | grep packetbeat) > /opt/packetbeat/service.created
  args:
    creates: /opt/packetbeat/service.created
  when: packetbeat_start_at_boot

# vi:ts=2:sw=2:et:ft=yaml
