---

# FIXME: configuration test would be nice

- name: Packetbeat configuration file
  template:
    src=etc/packetbeat/packetbeat.yml.j2
    dest="{{packetbeat_config_file}}"
    owner="{{packetbeat_user}}"
    group="{{packetbeat_group}}"
    mode=0640
  notify: packetbeat restart

# vi:ts=2:sw=2:et:ft=yaml
