---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: install.yml
  become: true
  tags: packetbeat_install

- include: config.yml
  become: true
  tags: packetbeat_config

- include: template.yml
  become: true
  tags: packetbeat_template

- name: Ensure Packetbeat is enabled and started at boot
  service:
    name: packetbeat
    enabled: yes
    state: started
  when: packetbeat_start_at_boot

# vi:ts=2:sw=2:et:ft=yaml
