---

- name: Packetbeat template file(s)
  copy:
    src: "{{ item }}"
    dest:  "{{ packetbeat_config_file | dirname }}/{{ item | basename }}"
    owner: "{{ packetbeat_user }}"
    group: "{{ packetbeat_group }}"
    mode: 0640
  with_items: "{{ packetbeat_templates }}"
  notify: packetbeat restart

# vi:ts=2:sw=2:et:ft=yaml
