---

- name: packetbeat start
  service: name=packetbeat state=started
  become: yes

- name: packetbeat stop
  service: name=packetbeat state=stopped
  become: yes

- name: packetbeat restart
  service: name=packetbeat state=restarted
  become: yes

# vi:ts=2:sw=2:et:ft=yaml
